
VATpercents: 21
basePrice: 10
childDiscountPercent: 50
luggageMultiplierPercent: 30

server:
  port: 8765

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

openapi:
  dwarfTicket:
    "base-path": /